version: '3.8'

services:
  zlibrary-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: zlibrary-app
    container_name: zlibrary-app
    ports:
      - "6126:6126"
    volumes:
      - ./download:/app/download
      - ./app.py:/app/app.py
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=production