FROM oven/bun:1 AS deps
WORKDIR /app
COPY package.json ./
COPY .npmrc ./
RUN bun install

FROM deps AS builder
COPY . .
RUN bun run build

FROM deps AS migrator
WORKDIR /app
COPY package.json ./
COPY drizzle.config.ts ./
COPY drizzle ./drizzle
COPY scripts ./scripts
COPY src/lib/server/infrastructure/db/schema.ts ./src/lib/server/infrastructure/db/schema.ts
CMD [ "bun", "run", "db:migrate" ]

FROM oven/bun:1 AS runtime
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=deps /app/node_modules node_modules/
COPY --from=builder /app/package.json ./
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "bun", "./build" ]
